language: node_js
node_js:
- "8.11.1"
before_install:
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
install:
- npm install
script:
- npm run build
cache:
  directories:
  - node_modules
git:
  depth: false